@startuml
scale 2
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
skinparam linetype ortho
hide empty members

skinparam padding 10
skinparam classPadding 20
skinparam classMargin 40
skinparam ranksep 100
skinparam nodesep 100
skinparam ArrowFontSize 14
skinparam ArrowColor black
skinparam ArrowThickness 1

class Main{
    +main( args:String[] )
}

package model {
    class Game{
        -_playerTurn : Integer
        -_blockedInsert[2]: Integer
        <<Create>> Game()
        +startGame()
        +initGameboard()
        +initGoals()
        +distributePlayersGoals()
        +initPlayersPosition()
        +nextPlayer()
        +movePlayer(posX, posY)
        +moveTilesLine()
        +addObserver()
        +rotateExtraTile(clockwise:Boolean)
        +moveExtraTile(clockwise:Boolean)
        +showExtraTile(): TileTemplate
        +checkGoal()
        +checkWinner()
        +notifyUpdateInitGameBoard(TileTemplate[49])
        +notifyUpdateRotateExtraTile(extraTileOrientation: Direction, extraTilePos:Integer[])
        +notifyUpdateMoveTilesLine(posExtraTile:Integer[])
        +notifyUpdatePlayerPosition(currentNumPlayer:Integer, oldPlayerPos:Integer[], newPlayerPos: Integer[], oldTile:TileTemplate, newTile:TileTemplate, playersOnTile:Player[])
        +notifyUpdateInitPlayersGoals(playersGoals:Entity[])
        +notifyUpdateMoveExtraTile(newPosExtraTile:Integer[], oldPosExtraTile:Integer[])
        +notifyUpdatePlayerPosition()
        +getCurrentPlayer(): Player
        +notifyUpdateGoalsDeck(numCurrentPlayer:Integer, posGoal:Integer)
        +notifyUpdateGameEnded(numCurrentPlayer:Integer)
    }

    class Player {
        -_position:Integer[]
        +<<Create>> Player()
        +addGoal(goal: Entity)
        +removeCurrentGoal()
        +getCurrentGoal():Entity
        +getGoalsDeck():Entity[]
        +getGoalsReach():Entity[]
        +getPosition:Integer[]
        +moveTo(posX: Integer, posY: Integer)
    }

    enum "<<enumeration>> \n Entity" {
        BLAZE_ROD
        BOW
        DIAMOND
        ENCHANTED_BOOK
        ENDER_PEARL
        GHAST_TEAR
        GLOWSTONE_POWDER
        GOLD_LINGOT
        GOLDEN_APPLE
        GREEN_POTION
        GUNPOWDER
        LAPIS_LAZULI
        MAGMA_CREAM
        NETHER_WART
        NETHERITE
        PAPER
        PORK_CHOP
        PURPLE_POTION
        RED_MUSIC_DISC
        RED_POTION
        REDSTONE
        SWORD
        TOTEM
        WHITE_MUSIC_DISC
        CHECKPOINT_1
        CHECKPOINT_2
        CHECKPOINT_3
        CHECKPOINT_4
    }

    enum "<<enumeration>> \n Direction" {
        NORTH
        SOUTH
        EAST
        WEST
    }

    abstract class TileTemplate <<abstract>> {
        -{static}rand:Random
        #_orientation:Directin
        #_entity:Entity
        #<<Create>> TileTemplate()
        #<<Create>> TileTemplate(orientation: Direction)
        +setOrientation(orientation: Direction)
        +getOrientation(): Direction
        +setEntity(entity: Entity)
        +getEntity(): Entit
        +{abstract}getEntries(): Boolean[4]
        +{abstract}getType(): String
    }

    class Hallway extends TileTemplate {
        +<<Create>> Hallway()
        +<<Create>> Hallway(orientation: Direction)
        +getEntries(): Boolean[4] {redefines}
        +getType(): String {redefines}
    }

    class Intersection extends TileTemplate {
        +<<Create>> Intersection()
        +<<Create>> Intersection(orientation: Direction)
        +getEntries(): Boolean[4] {redefines}
        +getType(): String {redefines}
    }

    class Corner extends TileTemplate {

        +<<Create>> Corner()
        +<<Create>> Corner(orientation: Direction)
        +getEntries(): Boolean[4] {redefines}
        +getType(): String {redefines}
    }

    class StartingTile extends Corner {
        +<<Create>> StartingTile()
        +<<Create>> StartingTile(orientation: Direction)
        +getEntries(): Boolean[4] {redefines}
        +getType(): String {redefines}
    }

    class TileFactory {
        +<<Create>> TileFactory()
        +createCorner(): Corner
        +createIntersection(): Intersection
        +createHallway(): Hallway
        +createStartingTile(): StartingTile
        +createCorner(orientation: Direction): Corner
        +createIntersection(orientation: Direction): Intersection
        +createHallway(orientation: Direction): Hallway
        +createStartingTile(orientation: Direction): StartingTile
    }

    class GameBoard {
        -_extraTilePosition:Integer[]
        +<<Create>> GameBoard()
        +init_board(tileFactory: TileFactory, entities:Entity[])
        +initCorners(tileFactory:tileFactory, entities:Entity[])
        +goalsDistribution(entities:Entity[])
        +insertExtraTile()
        +moveExtraTile(clockwise:Boolean)
        +rotateExtraTile(clockwise:Boolean)
        +getExtraTile(): TileTemplate
        +getSpecificTile(): TileTemplate
        +getGameBoardTiles():TileTemplate[][]
        +getExtraTilePosition(): Integer[]
    }

    interface GameObserver <<interface>> {
        +{abstract}updateInitGameBoard(gameBoardTiles:TileTemplate[][])
        +{abstract}updatePlayerPosition(currentNumPlayer:Integer, oldPlayerPos:Integer[], newPlayerPos: Integer[], oldTile:TileTemplate, newTile:TileTemplate, playersOnTile:Player[])
        +{abstract}updateMoveExtraTile(newPosExtraTile:Integer[], oldPosExtraTile:Integer[])
        +{abstract}updateMoveTilesLine(posExtraTile:Integer[])
        +{abstract}updateInitPlayersGoals(playersGoals:Entity[])
        +{abstract}updateRotateExtraTile(extraTileOrientation:Direction, extraTilePos:Integer[])
        +{abstract}updateGoalsDeck(numCurrentPlayer:Integer, posGoal: Integer[])
        +{abstract} updateNextPlaySamePlayer()
    }

}

package view {
    class GameWindow implements model.GameObserver {
        +<<Create>> GameWindow(controller: GameController)
        -{static}createGrid(gridCells:JLabel[][], rows:Integer, cols:Integer, cellWidth:Integer, cellHeight:Integer):JPanel
        -{static}createGoalsBook(goalsCells: JLabel[][] , rows:Integer, cols:Integer, slotSize:Integer, spacing:Integer):Jpanel
        -{static}createHotbar(hotbarCells JLabel[], slotSize:Integer, spacing:Integer):JPanel
        -{static}setImageInCell(cell:JLabel , image:BufferedImage )
        +updateInitGameBoard(gameBoardTiles:TileTemplate[][])
        +updatePlayerPosition(currentNumPlayer:Integer , oldPlayerPos:Integer[] , newPlayerPos:Integer[] , oldTile:TileTemplate , newTile:TileTemplate ,  playersOnTile:Player[])
        +updateRotateExtraTile(extraTileOrientation:Direction ,extraTilePos: Integer[] )
        +updateInitPlayersGoals(playersGoals:Entity[])
        +updateMoveExtraTile(newPosExtraTile:Integer[] , oldPosExtraTile: Integer[])
        +updateMoveTilesLine(posExtraTile: Integer[] )
        +updateGoalsDeck(numCurrentPlayer:Integer, posGoal:Integer[])
        +updateNextPlaySamePlayer()
        +updateGameEnded(numCurrentPlayerInteger)
    }

    class StartGameWindow implements model.GameObserver{
        +<<Create>> StartGameWindow(controller: GameController)
        +startGame()
    }
}

package controller {
    class GameController {
        -_game:Game
        +<<Create>> GameController()
        +movePlayerUp()
        +movePlayerDown()
        +movePlayerLeft()
        +movePlayerRight()
        +validatePlayerPosition()
        +validatePuttingExtraTile()
        +rotateExtraTile(clockwise:Boolean)
        +moveExtraTile(clockwise:Boolean)
        +addObserver(gameObserver: GameObserver)
        +play()
    }
}


TileFactory "1" ..> "1" TileTemplate : <<uses>>
TileFactory "1" ..> "1" Hallway : <<uses>>
TileFactory "1" ..> "1" StartingTile : <<uses>>
TileFactory "1" ..> "1" Intersection : <<uses>>
TileFactory "1" ..> "1" Corner : <<uses>>
TileFactory "1" ..> "1" "<<enumeration>> \n Direction" : <<uses>>
Player "1" ..> "1" "<<enumeration>> \n Entity" : <<uses>>

GameBoard "1" ..> "1" TileFactory : <<uses>>
TileTemplate "1" ..> "1" "<<enumeration>> \n Entity" : <<uses>>

TileTemplate "1" *-left-> "1\n #_orientation" "<<enumeration>> \n Direction" : > points to
TileTemplate "1" o-right-> "1\n #_entity" "<<enumeration>> \n Entity" : > has

Player "1" o-right-> "6\n- _goalsDeck" "<<enumeration>> \n Entity" : > has

Game "1" *-down-> "4\n  -_players" Player : > has
Game "1" *-up-> "1\n  -_gameboard" GameBoard : > has

GameBoard "1" o-left-> "49\n -_boardTiles" "TileTemplate" : > contains
GameBoard "1" o-> "1\n - _extraTile" "TileTemplate" : > has

GameController "1" *-down-> "1\n- _game" Game : > chooses

GameWindow "1" *-up-> "1\n- controller" GameController : > send user requests
EndingWindow "1" *-up-> "1\n- controller" GameController : > send user requests

Game "*" o-right-> "*\n- _observers" "GameObserver" : > observe
Game "24" *-right-> "*\n- _valableGoals" "<<enumeration>> \n Entity" : > contains
Game "1" *-right-> "*\n- _tileFactory" "TileFactory" : > has
Main "1" ..> "1" GameController : <<uses>>
Main "1" ..> "1" StartGameWindow : <<uses>>
@enduml