package model;

public enum Entity {
    BLAZE_ROD,
    BOW,
    DIAMOND,
    ENCHANTED_BOOK,
    ENDER_PEARL,
    GHAST_TEAR,
    GLOWSTONE_POWDER,
    GOLD_LINGOT,
    GOLDEN_APPLE,
    GREEN_POTION,
    GUNPOWDER,
    LAPIS_LAZULI,
    MAGMA_CREAM,
    NETHER_WART,
    NETHERITE,
    PAPER,
    PORK_CHOP,
    PURPLE_POTION,
    RED_MUSIC_DISC,
    RED_POTION,
    SWORD,
    TOTEM,
    WHITE_MUSIC_DISC
}
